name: build-sfx-mini-installer

on: 
  push:
    branches:
      - mini-installer
  pull_request:
    branches:
      - mini-installer

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: init
      working-directory: ${{github.workspace}}
      shell: pwsh
      run: |
          mkdir -p Tools
          Invoke-WebRequest -Uri https://github.com/Chuyu-Team/VC-LTL5/releases/download/v5.0.8/VC-LTL-5.0.8-Binary.7z -OutFile Tools\VC-LTL.7z
          7z x Tools\VC-LTL.7z -y -oTools\
          cp ".\Tools\VC-LTL helper for nmake.cmd" ./
    - name: build
      working-directory: ${{github.workspace}}
      shell: cmd
      run: |
          call .\Tools\Install.cmd
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          call "VC-LTL helper for nmake.cmd"
          cd .\C\Util\SfxSetup\
          nmake
          mt -manifest SfxSetup.manifest -outputresource:".\x86\7zS2.sfx;#1"
    - uses: actions/upload-artifact@v2
      with:
        name: 7zS2-MiniInstaller
        path: |
            .\C\Util\SfxSetup\x86\7zS2.sfx
jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: init
      working-directory: ${{github.workspace}}
      shell: pwsh
      run: |
          mkdir -p Tools
          Invoke-WebRequest -Uri https://github.com/Chuyu-Team/VC-LTL5/releases/download/v5.0.5/VC-LTL-5.0.5-Binary.7z -OutFile Tools\VC-LTL.7z
          7z x Tools\VC-LTL.7z -y -oTools\
          cp ".\Tools\VC-LTL helper for nmake.cmd" ./
    - name: build
      working-directory: ${{github.workspace}}
      shell: cmd
      run: |
          call .\Tools\Install.cmd
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          call "VC-LTL helper for nmake.cmd"
          cd .\C\Util\SfxSetup\
          nmake
          mt -manifest SfxSetup.manifest -outputresource:".\x86\7zS2.sfx;#1"
    - uses: actions/upload-artifact@v2
      with:
        name: 7zS2-MiniInstaller
        path: |
            .\C\Util\SfxSetup\x86\7zS2.sfx